### ISSUE TITLE
Dummy Plug has disabled Display 1 when I plug it in

### ISSUE THREAD

**Issue by hvddrift** [Nonary/MonitorSwapAutomation#10]
Hello, new user here. Not sure if this is the correct place but I am using MonitorSwapAutomation, sunshine and moonlight, so I guess it's a good place to start. Let’s just say I have made a big mistake that I don’t know how to fix

I had everything working, with a HDMI dummy switch and the swap was working perfectly. I wanted to disable the dummy when I was behind my PC because some apps would be dragged off onto the screen. I disabled Display 2 and when I started Moonlight my main screen went blank with no way of activating it again without unplugging the dummy

Is there a way to tell windows that I want to keep display 1 as the main display?

**Comment by Nonary** [comment]
It intentionally disables the other display when streaming, it swaps back when you stop streaming on Moonlight. You need to end the stream, not suspend it.

**Comment by Nonary** [comment]
No response from user.

**Comment by hvddrift** [comment]
Thank you. After a lot of trial and error I got it working. Thank you.
