### ISSUE TITLE
Chrome Remote Desktop

### ISSUE THREAD

**Issue by Bboy486** [Nonary/MonitorSwapAutomation#11]
Can this be used when using Chrome remote desktop from my laptop when the computer I am rdp to is using a 4k TV as the monitor?

**Comment by Nonary** [comment]
The script only swaps when you connect with Moonlight and Sunshine

**Comment by Bboy486** [comment]
Ok all good. Followup question in the setup step you mention adding the current monitor settings to 0 but you have two monitor values. Should the dummy file have both monitors and if so where do I get the monitor ID? 


Name=\\.\DISPLAY1
 MonitorID=MONITOR\GSMC0C8\{4d36e96e-e325-11ce-bfc1-08002be10318}\0009
 SerialNumber=LGTV
 BitsPerPixel=0
 Width=0
 Height=0
 DisplayFlags=0
 DisplayFrequency=0
 DisplayOrientation=0
 PositionX=0

**Comment by Nonary** [comment]
The monitor ID is different for every person and is obtained after exporting your configuration. I only provided my configuration as an example so people have a reference on what it is supposed to look like when configured.

Dummy file should only have **one** monitor enabled, which would be the dummy plug, this is mentioned in the setup instructions. Let me know if you have any other questions

**Comment by Nonary** [comment]
No response
