### ISSUE TITLE
hyper-v gpu-p and compatibility with iddSampleDriver - moonlight/sunshine

### ISSUE THREAD

**Issue by fusionneur** [Nonary/MonitorSwapAutomation#14]
talking about https://github.com/ge9/IddSampleDriver

i am currently testing a setup with hyper-v vm and iddSampleDriver with GPU-P acceleration, but sometimes when trying to connect (internal nat) with moonlight to sunshine hosted on the VM i get port issue related to video data and in sunshine log appears to detect duplicate display, and I am pretty much sure that hyper-v's display interferes with iddSample adapter. after failing several times to connect eventually connects and i can stream 4k 60fps with no problem on idd display, thus being able to play games or other gpu related activites in an isolated environment.

i was trying your tool but can't make it work. when trying to connect via moonlight will give me error about geforce experience, even if there is no such thing in the VM
I am not sure i got the instructions right, they're quite confusing and to be honest, they should be more simplified and examples given instead.

Display1 is the display as shown in MultiMonitorTool.exe when connecting via hyperv's enhanced rdp.
Display2 is the iddSampleDriver when i manage to connect eventually via moonlight.
Below my cfg files:

// dummy.cfg

[Monitor0]
Name=\\.\DISPLAY1
MonitorID=MONITOR\Default_Monitor\{4d36e96e-e325-11ce-bfc1-08002be10318}\0001
SerialNumber=
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0

[Monitor1]
Name=\\.\DISPLAY2
MonitorID=MONITOR\LEN4167\{4d36e96e-e325-11ce-bfc1-08002be10318}\0005
SerialNumber=
BitsPerPixel=32
Width=1920
Height=1080
DisplayFlags=0
DisplayFrequency=60
DisplayOrientation=0
PositionX=0
PositionY=0

// primary.cfg

[Monitor0]
Name=\\.\DISPLAY1
MonitorID=MONITOR\Default_Monitor\{4d36e96e-e325-11ce-bfc1-08002be10318}\0001
SerialNumber=
BitsPerPixel=32
Width=1366
Height=768
DisplayFlags=0
DisplayFrequency=66
DisplayOrientation=0
PositionX=0
PositionY=0

[Monitor1]
Name=\\.\DISPLAY2
MonitorID=MONITOR\LEN4167\{4d36e96e-e325-11ce-bfc1-08002be10318}\0005
SerialNumber=
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0

// settings.json
{
    "startDelay": 2,
    "gracePeriod": 60,
    "configSaveLocation": "%TEMP%",
    "dummyMonitorId": "MONITOR\\LEN4167\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0005"
}

**Comment by Nonary** [comment]
Even on Sunshine we don’t officially support virtual monitor solutions such as usbmidd or iddsampledriver because they contain many problems and do not function as reliably as a hardware solution such as a dummy plug.

With that aside, there is nothing I can do here to troubleshoot or even resolve this issue. IddSampleDrive and MultiMonitorTool are both external projects and only one of them is open source. For support or bug reports with the multi monitor tool you can reach out to nirsofer@yahoo.com
