### ISSUE TITLE
Remove requirement for DEBUG log level with Sunshine v0.21 release?

### ISSUE THREAD

**Issue by guaycuru** [Nonary/MonitorSwapAutomation#15]
Now that Sunshine v0.21 has been released with support for detecting what previously was only available in the logs, could we use that and allow restoring the log level back to the default, like was done for https://github.com/Nonary/AutoHDRSwitch and https://github.com/Nonary/ResolutionAutomation ?

**Comment by jriker1** [comment]
Look at the notes for the update of the [Readme.md] file on the main Code page.  Says it never required debug logs.

**Comment by guaycuru** [comment]
Awesome, thank you!
