### ISSUE TITLE
Reboot and using wrong monitor

### ISSUE THREAD

**Issue by jriker1** [Nonary/MonitorSwapAutomation#16]
Latest nightly of both Sunshine and MonitorSwap.  Been working fine but recently remotely rebooted.  Since I couldn't get in with Moonlight until I logged in once, I RDP into the Windows 11 computer and then used my batch file to disconnect:

```
@echo off 
ECHO You now have 30 seconds to start your project in Confire Player.
ECHO.
ECHO Your Remote Desktop session will then be disconnected from this computer.
TIMEOUT 5 /NOBREAK
for /f "usebackq skip=1 tokens=3" %%i in (`query user %USERNAME%`) do %windir%\System32\tscon.exe %%i /dest:console
exit 
```

I was then able to connect with Moonlight but was on Display 1 which is the one my monitor is connected to.  How do I get it to use Display 2 which is the HDMI dongle after a reboot?

[dummy.cfg.txt](https://github.com/Nonary/MonitorSwapAutomation/files/13181014/dummy.cfg.txt)
[primary.cfg.txt](https://github.com/Nonary/MonitorSwapAutomation/files/13181015/primary.cfg.txt)

At this point also if I go to the monitor attached it's blank so assuming when not connected thru Moonlight it's on thr 4k dongle and things are reversed.

**Comment by jriker1** [comment]
I went about some of this a different way but not helping overall.  So I figured out without getting into Microsoft accounts to auto login with my account.  I then used the Multi Monitor app to run the primary cfg.  With this:

1. I am able to connect pre 0.21.0 right after reboot, that said the monitor never comes up.  I only see the monitor in the bios startup screens.  When Windows kicks in the primary monitor goes blank and never comes back.  Ever.  Not sure if the primary is selected at anytime as it should be with my startup task running and how this module works but nothing shows.

**Comment by Nonary** [comment]
Well, if you're fine with automatic sign in, you can easily have it restore monitor by adding this to your startup commands (like task scheduler)

powershell.exe -executionpolicy bypass -windowstyle hidden -Command "& { . 'F:\sources\MonitorSwapAutomation\MonitorSwapper-Functions.ps1'; OnStreamEnd }"

Change the path to match your machine, what that does is essentially the same thing, it will poll until the monitor is restored, like when ending your stream.

**Comment by Nonary** [comment]
Might be a bug with multimonitor tool? Try the workaround #9

**Comment by jriker1** [comment]
I can give it a try but thinking I need to be on the primary monitor when doing this from what I'm reading.  Of course ccan't get the primary monitor to show.
