### ISSUE TITLE
Issue when resuming session

### ISSUE THREAD

**Issue by nem8** [Nonary/MonitorSwapAutomation#18]
My setup is:

Windows 11 desktop with an hdmi dongle running sunshine and your script.
Nvidia shield with moonlight which I have configured to start steam big picture.

Problem:
When resuming a running moonlight session, sunshine is using the wrong display.
I have to quit the session and restart it for the script to do it's magic and sunshine will then use the 4k hdmi dongle again.

I'm not convinced the issue is with the script considering the session is already running on the correct display, but I'm not sure..

**Comment by Nonary** [comment]
The intention of the script swapping back when you suspend because it's possible for someone to forget to terminate the stream and then they will have a difficult time restoring their primary monitor back.

**Comment by nem8** [comment]
I understand, it would be nice if there was an option to just keep the screen and resolution until client disconnects from Sunshine tho.
Is there an easy way for me to accomplish this?

**Comment by Nonary** [comment]
You can set the grace period to 2147483647, which would basically make it never swap unless you had the session paused for 68 years.

Or you can just delete these two lines in the script

https://github.com/Nonary/MonitorSwapAutomation/blob/master/MonitorSwapper.ps1#L46-L47C31

**Comment by nem8** [comment]
Thanks for the quick reply. I realize id made a few posts here without thanking you, so  thanks for the pretty awesome powershell scripts you make. They are quite usefull!
