### ISSUE TITLE
Passing the client resolution to the dummy configuration ?

### ISSUE THREAD

**Issue by zurce** [Nonary/MonitorSwapAutomation#21]
Given that Sunshine now supports environment variables like

Variables | Function
-- | --
SUNSHINE_CLIENT_WIDTH | The Width requested by the client
SUNSHINE_CLIENT_HEIGHT | The Height requested by the client
SUNSHINE_CLIENT_FPS | The FPS requested by the client
SUNSHINE_CLIENT_HDR | (true/false) if HDR is enabled by the client

Is there any way those can be pass to the dummy.cfg? I have two different setups (handheld remote play and desktop) and would love the ability to have the dummy properly switch between resolution and refresh rates on the fly

Is this something that could be achieved?

**Comment by Nonary** [comment]
It's possible but would require a lot of work with little benefit as you can do the same thing by just installing my three scripts that do this.

**Comment by Nonary** [comment]
Closing out as all of the functionality requested here can be done with my other scripts. I have no plans to merge them all together at this point.
