### ISSUE TITLE
Displays stay off whiel dummy plug is inserted

### ISSUE THREAD

**Issue by coolmansteel** [Nonary/MonitorSwapAutomation#22]
installed as directed and displays turned off when the stream started. but they never came back on, only solution is to unplug the dummy plug. Displays turn off as soon as the dummy is plugged back in and persists after uninstallation and reboot.

**Comment by Nonary** [comment]
Are you using the legacy version meant for GFE? That one will swap screens if you have any moonlight client connected, including if it is not actively streaming.

So if you left a computer or phone at the moonlight screen it will keep the dummy display active.

**Comment by Nonary** [comment]
No response
