### ISSUE TITLE
Restore the primary screen when starting the computer from a cold boot? 

### ISSUE THREAD

**Issue by harun911** [Nonary/MonitorSwapAutomation#23]
I'm using the GFE version. When I shutdown the PC through playnite on moonlight and boot my computer by pressing the power button, the PC is still connected to the dummy plug. I have to go into moonlight again and disconnect the connection for the computer to revert to my primary monitor. Is there a way to circumvent this? Like doing a check on boot to see if there's an active moonlight connection and if there isn't, revert back to my primary monitor?

**Comment by Nonary** [comment]
It's possible if you have automatic sign-in enabled, there isn't a way to restore monitor profiles for users at the login screen without them being logged in first.

Here's a workaround you can use that will revert on sign-in: https://github.com/Nonary/MonitorSwapAutomation/issues/16#issuecomment-1789887191
