### ISSUE TITLE
current_monitor_config.cfg does not match primary.cfg or dummy.cfg

### ISSUE THREAD

**Issue by kdliu86** [Nonary/MonitorSwapAutomation#24]
Not sure if this is a bug, I currently have 3 monitors on, dummy plug off.  current_monitor_config.cfg has my monitors out of order.

### current_monitor_config.cfg ###

`[Monitor0]
Name=\\.\DISPLAY1
MonitorID=MONITOR\GSM5BD3\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
SerialNumber=
BitsPerPixel=32
Width=2560
Height=1440
DisplayFlags=0
DisplayFrequency=180
DisplayOrientation=0
PositionX=0
PositionY=0
[Monitor1]
Name=\\.\DISPLAY2
MonitorID=MONITOR\ACI23D2\{4d36e96e-e325-11ce-bfc1-08002be10318}\0003
SerialNumber=FCLMTF234349
BitsPerPixel=32
Width=1920
Height=1080
DisplayFlags=0
DisplayFrequency=60
DisplayOrientation=0
PositionX=2560
PositionY=365
[Monitor2]
Name=\\.\DISPLAY3
MonitorID=MONITOR\GSM5A92\{4d36e96e-e325-11ce-bfc1-08002be10318}\0001
SerialNumber=
BitsPerPixel=32
Width=1920
Height=1080
DisplayFlags=0
DisplayFrequency=60
DisplayOrientation=0
PositionX=-1920
PositionY=360
[Monitor3]
Name=\\.\DISPLAY4
MonitorID=MONITOR\XMD009A\{4d36e96e-e325-11ce-bfc1-08002be10318}\0004
SerialNumber=
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0
`
### primary.cfg ###
`[Monitor0]
Name=\\.\DISPLAY1
MonitorID=MONITOR\XMD009A\{4d36e96e-e325-11ce-bfc1-08002be10318}\0004
SerialNumber=
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0
[Monitor1]
Name=\\.\DISPLAY2
MonitorID=MONITOR\GSM5A92\{4d36e96e-e325-11ce-bfc1-08002be10318}\0001
SerialNumber=
BitsPerPixel=32
Width=1920
Height=1080
DisplayFlags=0
DisplayFrequency=60
DisplayOrientation=0
PositionX=-1920
PositionY=360
[Monitor2]
Name=\\.\DISPLAY3
MonitorID=MONITOR\GSM5BD3\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
SerialNumber=
BitsPerPixel=32
Width=2560
Height=1440
DisplayFlags=0
DisplayFrequency=180
DisplayOrientation=0
PositionX=0
PositionY=0
[Monitor3]
Name=\\.\DISPLAY4
MonitorID=MONITOR\ACI23D2\{4d36e96e-e325-11ce-bfc1-08002be10318}\0003
SerialNumber=FCLMTF234349
BitsPerPixel=32
Width=1920
Height=1080
DisplayFlags=0
DisplayFrequency=60
DisplayOrientation=0
PositionX=2560
PositionY=365
`
### dummy.cfg ###
`[Monitor0]
Name=\\.\DISPLAY1
MonitorID=MONITOR\XMD009A\{4d36e96e-e325-11ce-bfc1-08002be10318}\0004
SerialNumber=
BitsPerPixel=32
Width=1280
Height=800
DisplayFlags=0
DisplayFrequency=60
DisplayOrientation=0
PositionX=0
PositionY=0
[Monitor1]
Name=\\.\DISPLAY2
MonitorID=MONITOR\GSM5A92\{4d36e96e-e325-11ce-bfc1-08002be10318}\0001
SerialNumber=
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=-0
PositionY=0
[Monitor2]
Name=\\.\DISPLAY3
MonitorID=MONITOR\GSM5BD3\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
SerialNumber=
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0
[Monitor3]
Name=\\.\DISPLAY4
MonitorID=MONITOR\ACI23D2\{4d36e96e-e325-11ce-bfc1-08002be10318}\0003
SerialNumber=FCLMTF234349
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0
`

**Comment by Nonary** [comment]
The current monitor config is only used to check to see if the restore had been completed, it is not used for anything else.  The reasoning why it might be out of order is because of how Windows will arbitrarily change the monitor display names and is the reason why we use profiles to restore the monitors back to what they where originally.
