### ISSUE TITLE
Mouse cursor missing on dummy virtual display

### ISSUE THREAD

**Issue by Julienc1** [Nonary/MonitorSwapAutomation#25]
Thanks for the work on this virtual display switcher - I set up the dummy and primary display profiles and everything seems to have been set up correctly.

When I start my moonlight session, the host pc correctly turns off the primary display and I see my virtual display on the client. However, I do not see any cursor at all, and no UI even highlights when i move my mouse. So it seems like the cursor is actually not on this display, and it's not just a UI issue. As soon as I end the session, the cursor reappears on the host machine as that display is re-enabled.

I am using virtual display from:
https://github.com/itsmikethetech/Virtual-Display-Driver

**Comment by Nonary** [comment]
Do you have a physical mouse attached to the host? This might be a Sunshine bug but not sure just yet.

**Comment by Nonary** [comment]
no response from user
