### ISSUE TITLE
Screens go black when dummy plug is connected

### ISSUE THREAD

**Issue by jmp7624** [Nonary/MonitorSwapAutomation#26]
I have checked through the closed issues and saw a few people having this issue but none of them actually said how to fix it. 

I have 3 monitors and I was testing this with a dummy plug to stream to the steamdeck. Everything worked great but then moonlight was just spinning when trying to exit a session. All of a sudden sunshine closed and moonlight couldnt connect anymore but I still had black screens. A restart didn't fix it and the only thing that worked was unplugging the dummy plug. I tried uninstalling everything but as soon as I plug that dummy plug in, the screens go black. I tried reinstalling everything again with a fresh version of sunshine and I still run into the same issue. My steam deck can connect to the dummy plug still but I have to unplug it every time. Its like there is a system file somewhere that shuts off the monitors when the dummy plug is inserted and I can't find it. 

I'm running windows 11 and I don't think I have the legacy version because I just installed it for the first time earlier today. 

I also tried saving the dummy.cfg and primary.cfg without the dummy plug installed and left everything at default in hopes it would reset it.

**Comment by Nonary** [comment]
Is it an actual dummy plug, or are you trying to use IDDSampleDriver, which has known issues exactly like this one for people who have iGPU and a GPU

**Comment by jmp7624** [comment]
I'm using a 4k dummy plug you connect to the HDMI. It was working find but it was after configuring this software that I had the issue. I do have a 7900XTX that I plug it into and my 7800X3D has video out but right now I have a sensor panel connected through it.

**Comment by nem8** [comment]
I did have this exact issue once after a game crashed and I had to reboot.
My solution was to delete the monitor setup profiles in registry that
"remembers" multimonitor setup iirc. It wasn't straight forward to find
this stuff as i had many different profiles there from over the years.



tor. 11. apr. 2024, 01:38 skrev jmp7624 ***@***.***>:

**Comment by jmp7624** [comment]
I will look into that and see what I can come up with. That sounds like it will fix the problem if I can find it in the registry. Do you know what yours was named by chance or can you point me in the right direction to find them?

**Comment by davisdmg** [comment]
Did you find how to delete it in the registry?

**Comment by davisdmg** [comment]
Fixed, here it is:

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\Configuration

**Comment by Nonary** [comment]
I did fix a black screen issue in v1.1.4 of the script, have you tried installing the latest version and trying again?

**Comment by Nonary** [comment]
No response from original poster, closing out issue
