### ISSUE TITLE
Not restoring original config when streaming is stopped

### ISSUE THREAD

**Issue by GiAmPoZ** [Nonary/MonitorSwapAutomation#27]
Hello everyone, i am pretty new and i am trying to set up everything as i intend.
My normal setup is a multimonitor with a 21:9 34" and a 16:9 24". I bought a HDMI dummy, following guides on the web, and i am trying to setup my streaming with both MonitorSwapAutomation and ResolutionMatcher.
I followed instructions and when i start streaming, both my monitor turn off according to my settings. When streaming ends, there is no way to revert things back, i have to remote desktop and manually launch a MonitorSwitcher.exe -load:Primary.xml (i am using workaround #9 because i was thinking that was my multimonitor setup that was messing things up. Anyway it does not work even without that workaround).
I attach my log file, and i really hope someone could help me.
Thanks in advance.
[log.txt](https://github.com/Nonary/MonitorSwapAutomation/files/14796142/log.txt)

**Comment by Nonary** [comment]
I would suggest using the nightly build of Sunshine and trying the monitor swap on that instead if this isn't working

https://github.com/LizardByte/Sunshine/releases/tag/nightly-dev

**Comment by Nonary** [comment]
Sorry meant this built https://github.com/LizardByte/Sunshine/pull/2032

**Comment by GiAmPoZ** [comment]
Thanks for your answer: basically i have to dl this version here https://github.com/LizardByte/Sunshine/releases/tag/nightly-dev right? Do i have to make a clean install?
Thanks.

**Comment by Nonary** [comment]
I reviewed your logs again and it is complaining that it can’t find the exported monitor configuration. I presume you did the workaround mentioned in #9 

However, you may have mistakenly deleted the old MultiMonitorTool in the scripts folder. This is still required for the script to function, it uses MultiMonitorTool to verify if the monitors have been restored, while the workaround is used for specifically just restoring the monitors.

**Comment by Nonary** [comment]
Cannot replicate or get response from user
