### ISSUE TITLE
Applying the script only to specific applications

### ISSUE THREAD

**Issue by junkimchi** [Nonary/MonitorSwapAutomation#32]
First off thank you very much for this as it is working beautifully with a dummy plug.

Not really an issue but was wondering if there was any way to just apply the script to certain applications. For example I only need it to run when I select my game launcher which is Playnite in moonlight and not when I click desktop. Hoping there is some command I can place in sunshine settings to enable this. It would help greatly because having my monitor mirrored is more convenient than shutting it off at times when I'm troubleshooting or need to do general Windows tasks. Thank you in advance.

**Comment by kdliu86** [comment]
I believe you can do it this way:

1. Open your sunshine config and duplicate the tab/window.  You should see the Command Preparations filled in by the MonitorSwapAutomation installer.
2. In the second tab, go to Applications, edit the Action for the application you're gonna use MSA for.  Click Add Commands under Command Preparations.
3. Copy the do and undo commands from the first tab into the second tab.  Click save.
4. In the first tab (Sunshine Configuration), delete the do/undo for MSA.

**Comment by junkimchi** [comment]
Ty for the quick response. I shall try this and report back.

**Comment by Nonary** [comment]
Add a new app to Sunshine and leave the command/detached fields empty, then check the option to disable global prep commands. That will launch the desktop without the script being activated.

You can also just copy and paste the do/undo commands from the global prep section to any application you’d like, then uninstall the script so it doesn’t activate on every application.
