### ISSUE TITLE
Instructions step 10 doesnt match

### ISSUE THREAD

**Issue by davisdmg** [Nonary/MonitorSwapAutomation#33]
Hi!

In the step 10 of the readme, it says:

Verify that the sunshine.conf file is configured properly, if successful the global_prep_cmd should look like this global_prep_cmd = [{"do":"powershell.exe -executionpolicy bypass -file "F:\sources\MonitorSwapAutomation\MonitorSwap-Dummy.ps1"","elevated":"false","undo":"powershell.exe -executionpolicy bypass -file "F:\sources\MonitorSwapAutomation\MonitorSwap-Functions.ps1" True"}]

However, we dont have the MonitorSwap-Dummy.ps1 file anymore. What file should we use?

**Comment by kdliu86** [comment]
MonitorSwapper.ps1 and MonitorSwapper-Functions.ps1

**Comment by Nonary** [comment]
will be fixed in next release https://github.com/Nonary/MonitorSwapAutomation/releases/tag/v1.1.6

removed the instruction step, wasn't really necessary
