### ISSUE TITLE
On 1.15, not recovering after exiting a game.

### ISSUE THREAD

**Issue by kdliu86** [Nonary/MonitorSwapAutomation#34]
```
Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      MonitorSwapp... BackgroundJob   Running       True            localhost            ...
3      MonitorSwapp... BackgroundJob   Running       True            localhost            ...
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Failed to verify dummy plug was activated, did you make sure dummyMonitorId was included and was properly escaped with double backslashes?
Processing event: Pipe-Terminated
INFO: Attempting to set primary screen, some displays may not activate until you return to the computer
INFO: Another session of MonitorSwapper was started, gracefully closing this one...
**********************
Windows PowerShell transcript end
End time: 20240508225204
**********************
```

Related https://github.com/Nonary/MonitorSwapAutomation/issues/31

I reverted all the way back to 1.05, does not have this issue.  I started getting the issue with 1.14 as well.

Expected action:
On launch of streamed game, dummy plug on, other monitors off.  On exit of streamed game, dummy plug off, other monitors on.

Actual:
On launch of streamed game, dummy plug on, other monitors off.  On exit of streamed game, dummy plug on, other monitors off.

I tested it around 20 or 30 times, the most common error was "Another session of MonitorSwapper was started, gracefully closing this one..."

**Comment by Nonary** [comment]
> Failed to verify dummy plug was activated, did you make sure dummyMonitorId was included and was properly escaped with double backslashes

I think you forgot to update the dummy plug after you installed the latest version again

I also identified an issue with logging that I am fixing in v1.1.6, can you try this version and then let me know if the logs show anything different, it will create up to 10 log files now.

https://github.com/Nonary/MonitorSwapAutomation/releases/tag/v1.1.6

**Comment by kdliu86** [comment]
Still not working, I also edited events.ps1 to include the workaround from #9 


primary.cfg

`[Monitor0]
Name=\\.\DISPLAY1
MonitorID=MONITOR\GSM5BD3\{4d36e96e-e325-11ce-bfc1-08002be10318}\0005
SerialNumber=
BitsPerPixel=32
Width=2560
Height=1440
DisplayFlags=0
DisplayFrequency=180
DisplayOrientation=0
PositionX=0
PositionY=0
[Monitor1]
Name=\\.\DISPLAY2
MonitorID=MONITOR\ACI23D2\{4d36e96e-e325-11ce-bfc1-08002be10318}\0003
SerialNumber=FCLMTF234349
BitsPerPixel=32
Width=1920
Height=1080
DisplayFlags=0
DisplayFrequency=60
DisplayOrientation=0
PositionX=2560
PositionY=365
[Monitor2]
Name=\\.\DISPLAY3
MonitorID=MONITOR\GSM5A92\{4d36e96e-e325-11ce-bfc1-08002be10318}\0004
SerialNumber=
BitsPerPixel=32
Width=1920
Height=1080
DisplayFlags=0
DisplayFrequency=60
DisplayOrientation=0
PositionX=-1920
PositionY=360
[Monitor3]
Name=\\.\DISPLAY4
MonitorID=MONITOR\XMD009A\{4d36e96e-e325-11ce-bfc1-08002be10318}\0006
SerialNumber=
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0
`

dummy.cfg

`[Monitor0]
Name=\\.\DISPLAY1
MonitorID=MONITOR\GSM5BD3\{4d36e96e-e325-11ce-bfc1-08002be10318}\0005
SerialNumber=
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0
[Monitor1]
Name=\\.\DISPLAY2
MonitorID=MONITOR\ACI23D2\{4d36e96e-e325-11ce-bfc1-08002be10318}\0003
SerialNumber=FCLMTF234349
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0
[Monitor2]
Name=\\.\DISPLAY3
MonitorID=MONITOR\GSM5A92\{4d36e96e-e325-11ce-bfc1-08002be10318}\0004
SerialNumber=
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0
[Monitor3]
Name=\\.\DISPLAY4
MonitorID=MONITOR\XMD009A\{4d36e96e-e325-11ce-bfc1-08002be10318}\0006
SerialNumber=
BitsPerPixel=32
Width=1280
Height=800
DisplayFlags=0
DisplayFrequency=60
DisplayOrientation=0
PositionX=0
PositionY=0
`

settings.json
`
{
    "startDelay": 4,
    "gracePeriod": 900,
    "configSaveLocation": "%TEMP%",
    "dummyMonitorId": "MONITOR\\XMD009A\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0006"
}
`

log 1 (launch game first time)
`
**********************
Windows PowerShell transcript start
Start time: 20240509190643
Username: Yen\Ken
RunAs User: Yen\Ken
Configuration Name: 
Machine: YEN (Microsoft Windows NT 10.0.22621.0)
Host Application: C:\windows\system32\windowspowershell\v1.0\powershell.exe -ExecutionPolicy Bypass -File D:\MonSwap_1.16\StreamMonitor.ps1 -async True
Process ID: 47532
PSVersion: 5.1.22621.2506
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2506
BuildVersion: 10.0.22621.2506
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\logs\log_20240509190643.txt
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Failed to verify dummy plug was activated, did you make sure dummyMonitorId was included and was properly escaped with double backslashes?
Processing event: MonSwap_1.16-Terminated
Unrecognized escape sequence. (119): {
    "startDelay": 4,
    "gracePeriod": 900,
    "configSaveLocation": "%TEMP%",
    "dummyMonitorId": "MONITOR\XMD009A\{4d36e96e-e325-11ce-bfc1-08002be10318}\0006"
}
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
    + PSComputerName        : localhost
Unrecognized escape sequence. (119): {
    "startDelay": 4,
    "gracePeriod": 900,
    "configSaveLocation": "%TEMP%",
    "dummyMonitorId": "MONITOR\XMD009A\{4d36e96e-e325-11ce-bfc1-08002be10318}\0006"
}
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
    + PSComputerName        : localhost

INFO: Another session of MonSwap_1.16 was started, gracefully closing this one...
**********************
Windows PowerShell transcript end
End time: 20240509190742
**********************
`

log 2
`**********************
Transcript started, output file is .\logs\log_20240509190805.txt
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Failed to verify dummy plug was activated, did you make sure dummyMonitorId was included and was properly escaped with double backslashes?
Processing event: MonSwap_1.16-Terminated
Unrecognized escape sequence. (119): {
    "startDelay": 4,
    "gracePeriod": 900,
    "configSaveLocation": "%TEMP%",
    "dummyMonitorId": "MONITOR\XMD009A\{4d36e96e-e325-11ce-bfc1-08002be10318}\0006"
}
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
    + PSComputerName        : localhost
Unrecognized escape sequence. (119): {
    "startDelay": 4,
    "gracePeriod": 900,
    "configSaveLocation": "%TEMP%",
    "dummyMonitorId": "MONITOR\XMD009A\{4d36e96e-e325-11ce-bfc1-08002be10318}\0006"
}
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
    + PSComputerName        : localhost

INFO: Another session of MonSwap_1.16 was started, gracefully closing this one...
**********************
Windows PowerShell transcript end
End time: 20240509190838
**********************`

log 3
`
**********************
Transcript started, output file is .\logs\log_20240509191054.txt
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Dummy plug activated
Processing event: MonSwap_1.16-Terminated
INFO: Another session of MonSwap_1.16 was started, gracefully closing this one...
**********************
Windows PowerShell transcript end
End time: 20240509191149
**********************
`

**Comment by Nonary** [comment]
You need to double slash the dummy monitor ID like this:

MONITOR\\XMD009A{4d36e96e-e325-11ce-bfc1-08002be10318}\\0006

**Comment by kdliu86** [comment]
> You need to double slash the dummy monitor ID like this:
> 
> ```
> MONITOR\\XMD009A{4d36e96e-e325-11ce-bfc1-08002be10318}\\0006
> ```

In primary.cfg and dummy.cfg?  It is doubleslashed in settings.json

**Comment by Nonary** [comment]
> > You need to double slash the dummy monitor ID like this:
> > ```
> > MONITOR\\XMD009A{4d36e96e-e325-11ce-bfc1-08002be10318}\\0006
> > ```
> 
> In primary.cfg and dummy.cfg? It is doubleslashed in settings.json

The log file is showing that it is not doubleslashed in the settings.json file

**Comment by kdliu86** [comment]
```
{
    "startDelay": 4,
    "gracePeriod": 900,
    "configSaveLocation": "%TEMP%",
    "dummyMonitorId": "MONITOR\\XMD009A\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0006"
}
```

this is my settings.json

I just ran it again, and got the doubleslash error:

https://i.imgur.com/T4aJGeN.png


Fresh multimonitortool cfg:

```
[Monitor0]
Name=\\.\DISPLAY1
MonitorID=MONITOR\ACI23D2\{4d36e96e-e325-11ce-bfc1-08002be10318}\0003
SerialNumber=FCLMTF234349
BitsPerPixel=32
Width=1920
Height=1080
DisplayFlags=0
DisplayFrequency=60
DisplayOrientation=0
PositionX=2560
PositionY=365
[Monitor1]
Name=\\.\DISPLAY2
MonitorID=MONITOR\GSM5BD3\{4d36e96e-e325-11ce-bfc1-08002be10318}\0005
SerialNumber=
BitsPerPixel=32
Width=2560
Height=1440
DisplayFlags=0
DisplayFrequency=180
DisplayOrientation=0
PositionX=0
PositionY=0
[Monitor2]
Name=\\.\DISPLAY3
MonitorID=MONITOR\GSM5A92\{4d36e96e-e325-11ce-bfc1-08002be10318}\0004
SerialNumber=
BitsPerPixel=32
Width=1920
Height=1080
DisplayFlags=0
DisplayFrequency=60
DisplayOrientation=0
PositionX=-1920
PositionY=360
[Monitor3]
Name=\\.\DISPLAY4
MonitorID=MONITOR\XMD009A\{4d36e96e-e325-11ce-bfc1-08002be10318}\0006
SerialNumber=
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0
```

**Comment by Nonary** [comment]
I don't see a double slash error in that image, are you streaming it again after exiting? The script also exits once you start another stream, so need to make sure it's the very latest log you retrieve, the other ones will almost always say exit gracefully if you're doing that.

**Comment by kdliu86** [comment]
```
**********************
Windows PowerShell transcript start
Start time: 20240509204147
Username: Yen\Ken
RunAs User: Yen\Ken
Configuration Name: 
Machine: YEN (Microsoft Windows NT 10.0.22621.0)
Host Application: C:\windows\system32\windowspowershell\v1.0\powershell.exe -ExecutionPolicy Bypass -File D:\MonSwap_1.16\StreamMonitor.ps1 -async True
Process ID: 50128
PSVersion: 5.1.22621.2506
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2506
BuildVersion: 10.0.22621.2506
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\logs\log_20240509204147.txt
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Dummy plug activated
Processing event: MonSwap_1.16-Terminated
INFO: Another session of MonSwap_1.16 was started, gracefully closing this one...
**********************
Windows PowerShell transcript end
End time: 20240509204227
**********************


```

What I did:

1.  Click moondeckstream icon for half-life 2.
2.  Game opens (monitors off, dummy on).
3.  Exit game
4.  No monitor recovery.

**Comment by Nonary** [comment]
Can you zip the entire folder and upload it here for me to look at it

**Comment by kdliu86** [comment]
[MonSwap_1.16.zip](https://github.com/Nonary/MonitorSwapAutomation/files/15269019/MonSwap_1.16.zip)

**Comment by Nonary** [comment]
You're missing the ampersand on the SetPrimaryScreen() 

it should be this

```
 & .\MonitorSwitcher.exe -load:Primary.xml
 ```
 
 I also suspect you might have a session stuck somehow, so, fix that line of code and then run this with Windows+R
 
 taskkill /im powershell.exe /f
 
 then try it again, then upload folder again if its still not working

**Comment by kdliu86** [comment]
[MonSwap_1.16.zip](https://github.com/Nonary/MonitorSwapAutomation/files/15269230/MonSwap_1.16.zip)

Still no recovery

**Comment by Nonary** [comment]
I am unable to replicate the issue on my side, at this point I say stick with 1.05 until further notice

**Comment by kdliu86** [comment]
Alrighty, thanks!

**Comment by Nonary** [comment]
Can you upload your sunshine.conf and sunshine.log file? Both are located  at C:\Program Files\Sunshine\config

**Comment by Nonary** [comment]
Fixed the uninstall bug in https://github.com/Nonary/MonitorSwapAutomation/releases/download/v1.1.6/MonitorSwapper_v1.1.6_rev_2.zip

**Comment by kdliu86** [comment]
[sunshine.log](https://github.com/Nonary/MonitorSwapAutomation/files/15275279/sunshine.log)
[sunshine_state.json](https://github.com/Nonary/MonitorSwapAutomation/files/15275280/sunshine_state.json)

FYI I removed the install prior to these logs, I'm also using a prep command for MoonDeckStream
```

        {
            "name": "MoonDeckStream",
            "output": "",
            "cmd": "\"C:\\Users\\Ken\\AppData\\Local\\Programs\\MoonDeckBuddy\\bin\\MoonDeckStream.exe\"",
            "exclude-global-prep-cmd": "false",
            "elevated": "false",
            "auto-detach": "false",
            "image-path": "",
            "wait-all": "true",
            "exit-timeout": "5",
            "prep-cmd": [
                {
                    "do": "powershell.exe -executionpolicy bypass -file \"D:\\MonitorSwapper\\MonitorSwapper.ps1\"",
                    "undo": "powershell.exe -executionpolicy bypass -file \"D:\\MonitorSwapper\\MonitorSwapper-Functions.ps1\" True",
                    "elevated": "false"
                },
                {
                    "do": "powershell.exe -executionpolicy bypass -WindowStyle Hidden -file \"D:\\ResolutionMatcher\\ResolutionMatcher\\ResolutionMatcher.ps1\"",
                    "undo": "powershell.exe -executionpolicy bypass -WindowStyle Hidden -file \"D:\\ResolutionMatcher\\ResolutionMatcher\\ResolutionMatcher-Functions.ps1\" True",
                    "elevated": "false"
                }
            ]
        },
```

**Comment by Nonary** [comment]
Okay, another pre-release revision 

https://github.com/Nonary/MonitorSwapAutomation/releases/download/v1.1.6/MonitorSwapper_v1.1.6_rev_3.zip

I changed how the named pipes terminate, they now support up to 10 connections at a time and I essentially spam messages to those pipes instead of using just one, I think that will make it less likely to terminate unintentionally. I also improved the logging significantly, you can go ahead and enable debug in the settings.json and upload the log if its still happening.

**Comment by kdliu86** [comment]
Is this supposed to be in settings.json for me?  I don't use autohdr, rtss limiter, or playnite watcher but it's auto filled in in settings.json

```
    "installationOrderPreferences": {
        "enabled": true,
        // Set the order which the scripts are installed in, if the scripts are currently out of order, they will be reinstalled in the order specified here.
        "scriptNames": [
            "MonitorSwapper",
            "ResolutionMatcher",
            "AutoHDR",
            "RTSSLimiter",
            "PlayNiteWatcher"
        ]
    }
```

**Comment by Nonary** [comment]
> Is this supposed to be in settings.json for me? I don't use autohdr, rtss limiter, or playnite watcher but it's auto filled in in settings.json
> 
> ```
>     "installationOrderPreferences": {
>         "enabled": true,
>         // Set the order which the scripts are installed in, if the scripts are currently out of order, they will be reinstalled in the order specified here.
>         "scriptNames": [
>             "MonitorSwapper",
>             "ResolutionMatcher",
>             "AutoHDR",
>             "RTSSLimiter",
>             "PlayNiteWatcher"
>         ]
>     }
> ```

Yeah that is correct, if you happen to have those it make sure they are in proper order, if not, it doesnt do anything

**Comment by kdliu86** [comment]
Happy to report it's working as well as 1.05.  I did replace `& .\MonitorSwitcher.exe -load:Primary.xml`



log 1

```
**********************
Windows PowerShell transcript start
Start time: 20240515135520
Username: Yen\Ken
RunAs User: Yen\Ken
Configuration Name: 
Machine: YEN (Microsoft Windows NT 10.0.22621.0)
Host Application: C:\windows\system32\windowspowershell\v1.0\powershell.exe -ExecutionPolicy Bypass -Command & 'D:\MonSwap_1.16\StreamMonitor.ps1' -scriptName MonitorSwapper -sib 1
Process ID: 13884
PSVersion: 5.1.22621.2506
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2506
BuildVersion: 10.0.22621.2506
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\logs\log_1715781320.txt
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Dummy plug activated
Processing event: NewSession
A new session of this script has been started. To avoid conflicts, this session will now terminate. This is a normal process and not an error.
**********************
Windows PowerShell transcript end
End time: 20240515135534
**********************
```

log 2
```

**********************
Windows PowerShell transcript start
Start time: 20240515135531
Username: Yen\Ken
RunAs User: Yen\Ken
Configuration Name: 
Machine: YEN (Microsoft Windows NT 10.0.22621.0)
Host Application: C:\windows\system32\windowspowershell\v1.0\powershell.exe -ExecutionPolicy Bypass -Command & 'D:\MonSwap_1.16\StreamMonitor.ps1' -scriptName MonitorSwapper -sib 1
Process ID: 24360
PSVersion: 5.1.22621.2506
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2506
BuildVersion: 10.0.22621.2506
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\logs\log_1715781332.txt
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Dummy plug activated
Processing event: Terminate
INFO: Stream has ended, now invoking code
The process cannot access the file because another process has locked a portion of the file.

    + CategoryInfo          : ReadError: (C:\Users\Ken\Ap...itor_config.cfg:String) [Get-Content], IOException
    + FullyQualifiedErrorId : GetContentReaderIOError,Microsoft.PowerShell.Commands.GetContentCommand
    + PSComputerName        : localhost
The process cannot access the file because another process has locked a portion of the file.

    + CategoryInfo          : ReadError: (C:\Users\Ken\Ap...itor_config.cfg:String) [Get-Content], IOException
    + FullyQualifiedErrorId : GetContentReaderIOError,Microsoft.PowerShell.Commands.GetContentCommand
    + PSComputerName        : localhost

INFO: Primary monitor(s) have been successfully restored!
**********************
Windows PowerShell transcript end
End time: 20240515135632
**********************

```

**Comment by Nonary** [comment]
Awesome, I went ahead and promoted v1.1.6 to main release now
