### ISSUE TITLE
GPU Spikes 

### ISSUE THREAD

**Issue by bougeros** [Nonary/MonitorSwapAutomation#35]
When the script is running I noticed some intermittent stuttering in-game. After further investigation it seems to be a GPU usage spike to 100% every 10 seconds. I have dual monitors which I've 0'd out in my primary.cfg, leaving only the dummy (a virtual monitor using https://github.com/itsmikethetech/Virtual-Display-Driver). When the GPU Spikes I can see in Windows' display options that it's creating and removing an invisible monitor (nothing changes on-screen besides the stutter). Could this be something in the script that's being checked every 10 seconds?

**Comment by Nonary** [comment]
Post logs for the script

**Comment by bougeros** [comment]
[log.txt](https://github.com/Nonary/MonitorSwapAutomation/files/15287992/log.txt)
I've double checked that the dummyid is set in the settings.json, with double backslashes as well.

**Comment by Nonary** [comment]
Try the new release, which fixes a bug in the logging, although keep in mind logs will be stored in the logs folder now

**Comment by Nonary** [comment]
No response, closing out
