### ISSUE TITLE
Unable to interact with mouse after stream

### ISSUE THREAD

**Issue by OsaCode** [Nonary/MonitorSwapAutomation#36]
My hardware :

Host: AMD GPU and CPU. 2 physical monitors. 1 dummy virtual 4k monitor. I use monitor swap automation and it correctly deactivates my 2 monitors and activates my dummy one.

Client: SteamDeck, streaming in native resolution as well as in 4k docked.

Steps to reproduce:

1. Start the stream
2. Close the stream

Issue:
Impossible to interact with anything with the mouse other than the last window on the host.
If Steam was opened and in focus before closing the stream, then I will be able to click anything inside the window, but not anything else.
I have to press windows and tab to restart/stop my computer

Restarting the stream does not solve the issue, I can do nothing from the client as well once I have quit once.

Restarting the computer fixes it though.

**Comment by Nonary** [comment]
That doesn't make any sense, just to double check are you using Sunshine installed as a service?

And you're also not trying to play a game that uses anticheat, such as LoL or Valorant.

**Comment by OsaCode** [comment]
I am not trying to play any of these games, but I do have Vanguard installed

**Comment by OsaCode** [comment]
I identified the problem and that is not caused by MonitorSwapAutomation, sorry !
