### ISSUE TITLE
Not Switch back to primary monitor

### ISSUE THREAD

**Issue by bayramog** [Nonary/MonitorSwapAutomation#37]
Hey there,

Recently I have started to get some error which prevents return to primary monitor. I am adding the latest log from the script.
[log_1716628981.txt](https://github.com/Nonary/MonitorSwapAutomation/files/15448196/log_1716628981.txt)

**Comment by Nonary** [comment]
That looks like a WMI corruption to me, please run the following in a command prompt that is admin

```
sfc /scannow
``` 

and then after rebooting

```
net stop winmgmt
winmgmt /salvagerepository
net start winmgmt
```

**Comment by Nonary** [comment]
No response from user.
