### ISSUE TITLE
Restore before installation 

### ISSUE THREAD

**Issue by danosito** [Nonary/MonitorSwapAutomation#41]
This script is very bad.
I used it by instruction, successfully connected, but my primary monitor was black. I've rebooted, and my PRIMARY AND THE ONLY monitor was still black, sunshine wasn't connecting. So, i haven't monitor. I've booted in the safe mode, deleted the script, but this didn't help. I've cleared sunshine config, no. How do i restore?

**Comment by danosito** [comment]
My pc:
Only dedicated graphics (rtx 3060)
IddSampleDriver(worked completely fine before this script)
And this script

**Comment by danosito** [comment]
I've fixed it with deleting the virtual monitor from the system. But when connecting monitor again, my primary monitor becomes black. What a stupid script, why it's so hard to fix issues after running this shit

**Comment by Nonary** [comment]
Closing for user error.

**Comment by Nonary** [comment]
Since you’re clearly still young, here’s a life lesson: if you don’t treat others with respect, you can’t expect it in return. Please feel free to resubmit this issue, describing all the steps you’ve tried and what’s happening, and we can go from there in a more professional tone.
