### ISSUE TITLE
Is it possible to restore monitors cfg faster?

### ISSUE THREAD

**Issue by kanjieater** [Nonary/MonitorSwapAutomation#42]
The basic setup seems to work well for me without the  workaround at #9 . However, I also noticed the slow "restore". It seems like it iterates through the monitors and turns them back on one by one with a few seconds of delay between each monitor. I have a 4 monitor setup so it does take a while to restore. I'm wondering if there's a way to restore the whole primary.cfg at once, like MultiMonitorTool.exe does if you load it through the GUI.

**Comment by Nonary** [comment]
Try the workaround mentioned on #9 and see if it does better for you
