### ISSUE TITLE
Moonlight no longer connecting after MonitorSwapAutomation Install

### ISSUE THREAD

**Issue by AidenPisan** [Nonary/MonitorSwapAutomation#43]
After installing MonitorSwapAutomation, my moonlightclient is no longer able to connect to my host pc on the same network, It will give a "connecting" loading screen forever if I try connecting like usual. I've tried restarting sunshine, the host computer, and re-pairing moonlight client. I recieved no errors when exectuting the BAT file for this script and Sunshine appears to be working on the host computer(I'm able to use the web gui and execute commands like normal). My moonlight client is the community build for LG smart TV which worked perfectly before. I'm running v0.23.1 sunshine with a Virtual Display Driver (23.12.2 HDR, Windows 11 22H2+), and v1.1.9 MonitorSwapAutomation.

Here is my primary.cfg:
`[Monitor0]
Name=\\.\DISPLAY1
MonitorID=MONITOR\ACR067E\{4d36e96e-e325-11ce-bfc1-08002be10318}\0008
SerialNumber=
BitsPerPixel=32
Width=2560
Height=1440
DisplayFlags=0
DisplayFrequency=120
DisplayOrientation=0
PositionX=0
PositionY=0
[Monitor1]
Name=\\.\DISPLAY9
MonitorID=MONITOR\LNX0000\{4d36e96e-e325-11ce-bfc1-08002be10318}\0003
SerialNumber=
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0`

dummy.cfg:
`[Monitor0]
Name=\\.\DISPLAY1
MonitorID=MONITOR\ACR067E\{4d36e96e-e325-11ce-bfc1-08002be10318}\0008
SerialNumber=
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0
[Monitor1]
Name=\\.\DISPLAY9
MonitorID=MONITOR\LNX0000\{4d36e96e-e325-11ce-bfc1-08002be10318}\0003
SerialNumber=
BitsPerPixel=32
Width=3840
Height=2160
DisplayFlags=0
DisplayFrequency=120
DisplayOrientation=0
PositionX=2560
PositionY=0`

settings.json:
`{
    "debug": false,
    "startDelay": 4, // In order to prevent the Sunshine stream from freezing, this will wait 4 seconds before starting the next prep command in Sunshine. Feel free to reduce this number if you are not experiencing any issues.
    "gracePeriod": 900,
    "configSaveLocation": "%TEMP%",
    "dummyMonitorId": "MONITOR\\LNX0000\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0003", // Insert Monitor ID Here, don't forget to double slash to escape; e.g. "MONITOR\\XMD009A\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0010",
    "enableStrictRestoration": false, // If true, the script will adjust how it verifies the primary monitor is active, reducing false positives, but may cause issues on some setups.
    "installationOrderPreferences": {
        "enabled": true,
        // Set the order which the scripts are installed in, if the scripts are currently out of order, they will be reinstalled in the order specified here.
        // All of these scripts are optional and will not impact your experience if they are not installed.
        // However, I am shamelessly plugging in links to the scripts here, so you can easily find them.
        "scriptNames": [
            "MonitorSwapper", // https://github.com/Nonary/MonitorSwapAutomation/releases/latest  (Swaps the primary monitor to a dummy plug and then back when finished.)
            "ResolutionMatcher", // https://github.com/Nonary/ResolutionAutomation/releases/latest (Automatically sets the resolution to the same as the client streaming.)
            "AutoHDR", // https://github.com/Nonary/AutoHDRSwitch/releases/latest (Automatically enables HDR if the client is streaming HDR content.)
            "RTSSLimiter", // https://github.com/Nonary/RTSSLimiter/releases/latest (Limits the host framerate to the client's streaming framerate to reduce microstuttering)
            "PlayNiteWatcher" // https://github.com/Nonary/PlayniteWatcher/releases/latest (Export any game with the box art in Playnite to the Moonlight client. Enables automatic stream termination and ability to close games from Moonlight.)
        ]
    }
}`

**Comment by Nonary** [comment]
Increase the start delay to 8 seconds and see if that works, if it does, feel free to reduce it to 6 or 5 seconds to see if that is long enough for it to work.

Also make sure that you didn't configure a monitor in the sunshine settings, it needs to be deleted if you did, otherwise it will not work properly.

**Comment by ds0tr0** [comment]
> Increase the start delay to 8 seconds and see if that works, if it does, feel free to reduce it to 6 or 5 seconds to see if that is long enough for it to work.
> 
> Also make sure that you didn't configure a monitor in the sunshine settings, it needs to be deleted if you did, otherwise it will not work properly.

Already working. Reinstaled virtual driver exactly the same way as the first time... Go figure...

**Comment by Nonary** [comment]
No response
