### ISSUE TITLE
Option to restore monitors on boot

### ISSUE THREAD

**Issue by Mrsalai** [Nonary/MonitorSwapAutomation#45]
So basically if you shutdown the pc then the monitors wont restore, and you cannot stream.
You need to press Win+Ctrl+Shift+B to do a driver reset which is not great if you are far away from the pc.

**Comment by Mrsalai** [comment]
I got a temporary solution if anyone is looking for it though:
create a bat file and paste in this: [YOUR FOLDER]\MultiMonitorTool.exe /LoadConfig [YOUR FOLDER]\primary.cfg
Then win+ R enter: taskschd.msc, create a task, run at every boot, and select your bat file.
This way your original monitor config will be restored at every boot.
Note if you change your monitor config, you need to edit your primary.cfg.

**Comment by JumboJoe55** [comment]
I just experienced this issue yesterday when I shut down my host PC with Moonlight. This morning, I can't turn on (or use) my host pc as it is still using the dummy monitor. Any idea how to force it to the primary cfg so I can try your solution? Thanks

**Comment by Mrsalai** [comment]
just do WIN CTRL SHIFT B.
And it should restore it, although you probably need a reboot to use sunshine again.

**Comment by Nonary** [comment]
I have looked into this in the past and there isn't an API that Microsoft provides that allows this to work at System/Administrator level to change the settings of users. As such this won't be implemented as a feature unless Microsoft updates the display settings API to allow that.
