### ISSUE TITLE
Any way to restore monitors in a preferred order?

### ISSUE THREAD

**Issue by terenceo** [Nonary/MonitorSwapAutomation#47]
Just curious if there's any way to restore the primary monitor configuration so that the monitors in my multi-monitor setup get re-enabled in a specific order. The reason I'm asking this is because my vertically oriented monitor is re-enabled first which leads to any open applications getting resized for this monitor. After my primary monitor gets enabled all windows are in a vertical sized window. 

Not a huge bug, more of an annoyance to re-size all open windows accordingly.

Thanks for the awesome script!

**Comment by SquiIIiam** [comment]
Seeing the same behavior with my vertical secondary monitor setup.

**Comment by Nonary** [comment]
Can you try latest release which uses MonitorSwitcher?

https://github.com/Nonary/MonitorSwapAutomation/releases/tag/v2.0

**Comment by Nonary** [comment]
No response from user
