### ISSUE TITLE
Problem with Virtual Monitor when HDR enabled

### ISSUE THREAD

**Issue by Kilvearn** [Nonary/MonitorSwapAutomation#48]
Hello,

I'm using MonitorSwapAutomation to switch to my virtual monitor who has HDR enabled.
I noticed that, when I configure the "primary.cfg" to "disable" the virtual screen after a moonlight session, the next time I use Moonlight, the  screen colors have a big problem (over saturated, false colors,...). I have to disable and enable HDR in Windows settings to have correct colors again.
The problem doesn't occur if, in the "primary.cfg" file, I leave the virtual monitor always connected as secondary screen. In this case, HDR colors are always ok after a session.
I don't know if it's a known issue with HDR ?
Thanks a lot in advance

**Comment by Nonary** [comment]
Not an issue with the swap program, it is an issue with the virtual display driver. You can workaround it by installing this HDR script and enabling the IDDSampleFix option in settings: https://github.com/Nonary/AutoHDRSwitch/releases/latest
