### ISSUE TITLE
Primary Display Not Switching of On Stream Start

### ISSUE THREAD

**Issue by sysmoon14** [Nonary/MonitorSwapAutomation#49]
I had this all set up and working nicely, but yesterday I updated to Windows 11 24H2 to get the nice AMD CPU benefits and since then my main monitor doesn't switch off when I start a stream. Instead my virtual display (MikeTheTech HDR) and primary display are both active. Ending the stream correctly reverts back to only the primary monitor.

I did notice that my monitor IDs changed after the update, so I updated my configs to match and reinstalled the script.

Primary.cfg
```[Monitor0]
Name=\\.\DISPLAY1
MonitorID=MONITOR\BNQ7F66\{4d36e96e-e325-11ce-bfc1-08002be10318}\0000
SerialNumber=T9L01775019
BitsPerPixel=32
Width=2560
Height=1440
DisplayFlags=0
DisplayFrequency=120
DisplayOrientation=0
PositionX=0
PositionY=0
[Monitor1]
Name=\\.\DISPLAY6
MonitorID=MONITOR\LNX0000\{4d36e96e-e325-11ce-bfc1-08002be10318}\0001
SerialNumber=
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0
```

Dummy.cfg
```[Monitor0]
Name=\\.\DISPLAY1
MonitorID=MONITOR\BNQ7F66\{4d36e96e-e325-11ce-bfc1-08002be10318}\0000
SerialNumber=T9L01775019
BitsPerPixel=0
Width=0
Height=0
DisplayFlags=0
DisplayFrequency=0
DisplayOrientation=0
PositionX=0
PositionY=0
[Monitor1]
Name=\\.\DISPLAY6
MonitorID=MONITOR\LNX0000\{4d36e96e-e325-11ce-bfc1-08002be10318}\0001
SerialNumber=
BitsPerPixel=32
Width=1920
Height=1080
DisplayFlags=0
DisplayFrequency=60
DisplayOrientation=0
PositionX=0
PositionY=0
```

Debug log attached from my latest run. Am I missing something obvious, the windows update could be a red herring, but it's the only think I can think of that's really changed.

[log_1724862148.txt](https://github.com/user-attachments/files/16786236/log_1724862148.txt)

**Comment by sysmoon14** [comment]
Experienced the same issue when trying https://github.com/Cynary/sunshine-virtual-monitor

So the issue must be with MultiMonitotTool. Either something in my setup or it doesn't like 24H2

**Comment by j-scrizz** [comment]
Yep same issue here on 24h2. Did you manage to find a fix?

**Comment by germsathome** [comment]
Just to chime in, I reverted from 24H2 and everything seems to be working after the roll back

**Comment by Lcdiniz** [comment]
Same issue here, but Intel CPU on 24H2.

**Comment by Foleychris** [comment]
Seeing the same thing, 24H2 (OS Build 26.100.2033)

**Comment by Foleychris** [comment]
For anyone else seeing this, MultiMonitor tool  Version 2.15 fixed this. Swap it out in your folder and should fix it. The release notes specifically call out this bug as well.

**Comment by Nonary** [comment]
Updated MultiMonitorTool in the release to 2.15
