### ISSUE TITLE
RDP Accidently

### ISSUE THREAD

**Issue by jriker1** [Nonary/MonitorSwapAutomation#5]
I am using this automation to switch between primary monitor and my 4k HDR emulator dongle when remote on my editing monitor.  It's been working great thet day I've been trying it however I accidently RDP'd directly into the system on Windows.  Now when I run Moonlight it fails with error 503.  Any idea what's up or how to fix it?

**Comment by Nonary** [comment]
Resolved on Discord, basically RDP breaks Sunshine and you have to disconnect using a command in PowerShell

```
$session = (query session | Select-String $env:USERNAME) -split " " | Where-Object { $_ } | Select-Object -Index 2
    & tscon $session /dest:console
```

Tip, if you want to make this easy, you can add a command to PowerShell called "End-RDPSession"


The following below is written by artificial intelligence with my own touches....

1. **Locate your PowerShell Modules folder**: 
    The first step is to make sure you have a folder in your documents directory where you can install custom modules. This folder is usually at this path:
    ```
    C:\Users\<yourUsername>\Documents\WindowsPowerShell\Modules
    ```
    You can find this path by typing `$env:USERPROFILE` in PowerShell and appending "\Documents\WindowsPowerShell\Modules" to the output. If the "WindowsPowerShell" and "Modules" directories do not exist, you need to create them.

2. **Move the downloaded folder to the Modules directory**: 
    The next step is to place the folder containing the psm1 file into the 'Modules' directory that you located (or created) in the first step. Make sure that the module folder name and the psm1 file name are the same. This is a requirement for PowerShell to correctly identify and load the module.

3. **Unblock the files**: 
    Since the file is downloaded from the internet, it might be blocked. To unblock it, you can use the `Unblock-File` cmdlet in PowerShell. Before running these commands, close any PowerShell windows.
    Open a new PowerShell window as an Administrator by searching for "PowerShell" in the Start menu, right-clicking on it, and selecting "Run as Administrator". 

    In the PowerShell window, change to the directory where your psm1 file is located. For instance, if your module's name is "MyModule", the command would look like this:
    ```
    cd $env:USERPROFILE\Documents\WindowsPowerShell\Modules\MyModule
    ```
    Then, unblock the file with this command:
    ```
    Get-ChildItem -Recurse | Unblock-File
    ```
    This will unblock all the files in that directory and its subdirectories. 

4. **Load the module automatically**: 
   On restarting powershell, observe a new command will be available called End-RDPSession

Remember, if you ever download updates to your module, you may need to repeat step 3 to unblock the updated files.
