### ISSUE TITLE
How would you configure this + ResolutionAutomation with multiple clients of different resolutions?

### ISSUE THREAD

**Issue by glottisfaun0000** [Nonary/MonitorSwapAutomation#50]
I have MonitorSwapAutomation and ResolutionAutomation set up for my 1080p handheld, but today I wanted to use Moonlight on my laptop and realized I'll be stuck at 1920x1080 via my dummy monitor. How can I create and install a second configuration for a different resolution match?

**Comment by Nonary** [comment]
Install ResolutionAutomation **after** you installed MonitorSwap. Adjust start delay of MonitorSwap in settings if the resolution change is happening before the monitor swap completes. Also upload the logs of MonitorSwap so I can make sure you have configured it properly
