### ISSUE TITLE
Audio Source did not restore to default

### ISSUE THREAD

**Issue by Flipfuchs** [Nonary/MonitorSwapAutomation#53]
Thank You very much for your effort doing this! working great so far!

After closing the stream and returning to my main Monitor the audio source still remains "Steam streaming speakers" and not go back to my default audio via hdmi.

**Comment by Nonary** [comment]
That is unrelated to this script, that is caused by Moonlight if you enable the "Mute PC Speakers" option. And should be restored when ending the session in Moonlight (instead of suspending it). Please reach out to Moonlight discord if you need anymore assistance.
