### ISSUE TITLE
Lag after restoring primary.cfg

### ISSUE THREAD

**Issue by nbriffa** [Nonary/MonitorSwapAutomation#56]
After I switch back to my correct monitor configuration, I will get about 1 second of intense lag, in 20 second intervals. This only started happening after I started using MonitorSwapAutomation.

**Comment by nbriffa** [comment]
I've confirmed that this is related to PowerShell staying open, and trying to run a command of some kind. Manually ending the task seems to fix the issue.

**Comment by djoli** [comment]
Noticed the same thing when I started using this. Given the lack of response on the issue, I might take an attempt to fix it.

**Comment by djoli** [comment]
After some diagnosing, I found the clean up process was getting stuck in an infinite loop as it was unable to determine my primary monitor. This was because, at some point in the set up process, I modified the primary.cfg and dummy.cfg files to escape slashes in the monitor names.

Undoing this change caused the script to succeed and shut down correctly, and so far i've not noticed any side effects.

If you did the same thing as me, perhaps undo that change and see if it solves the problem for you.

**Comment by djoli** [comment]
Your monitor names don't look quite right, according to my testing.

Name=\\.\DISPLAY5
MonitorID=MONITOR\LNX0000\{4d36e96e-e325-11ce-bfc1-08002be10318}\0000
SerialNumber=
BitsPerPixel=32
Width=2560
Height=1600
DisplayFlags=0
DisplayFrequency=90
DisplayOrientation=0
PositionX=0
PositionY=0

Note the double \\ at the start.

If that doesn't work, try replacing the Helpers.ps1 file in the directory with the one in this file. [MonitorSwapper.zip](https://github.com/user-attachments/files/17946884/MonitorSwapper.zip). It just hard codes the debugging. Then clear out all of the logs inside the logs folder, start and stop a stream, and upload the log it created so I can try to diagnose.

**Comment by djoli** [comment]
Noticed that github seems to strip the slashes...

```
Name=\\.\DISPLAY5
MonitorID=MONITOR\LNX0000\{4d36e96e-e325-11ce-bfc1-08002be10318}\0000
SerialNumber=
BitsPerPixel=32
Width=2560
Height=1600
DisplayFlags=0
DisplayFrequency=90
DisplayOrientation=0
PositionX=0
PositionY=0
```

**Comment by nbriffa** [comment]
Ah so it does, here is the blocked version of mine.

`[Monitor0]
Name=\\.\DISPLAY1
MonitorID=MONITOR\AUS2722\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
SerialNumber=L4LMQS044358
BitsPerPixel=32
Width=2560
Height=1440
DisplayFlags=0
DisplayFrequency=144
DisplayOrientation=0
PositionX=3440
PositionY=0`

Thanks for all your help, but due to Issue #44 I've decided to just move to MonitorSwitcher, which has been flawless.

**Comment by Nonary** [comment]
The latest version of this script now uses MonitorSwitcher due to issues with 24H2 and general reliability seems to be better.
