### ISSUE TITLE
Games not launching on secondary/dummy monitor

### ISSUE THREAD

**Issue by tconroy** [Nonary/MonitorSwapAutomation#57]
My setup is a primary ultrawide monitor, and a dummy 4k HDMI plug.

The script works correctly: When I launch Moonlight, the stream connects to my desktop, I see it switch from my ultrawide to 4k dummy, and big picture opens at the correct resolution.

When I launch a game, the screen goes black, and I can hear the game audio, but I cannot see the game.

If I alt-tab on the host PC, I can see the game launched in the open applications, but clicking to it doesn't seem to properly focus it. 

Any ideas? it seems almost like the games are trying to launch at the resolution of the primary display and not the resolution of the dummy/active display.

**Comment by Nonary** [comment]
Try the latest release to see if it works better: https://github.com/Nonary/MonitorSwapAutomation/releases/tag/v2.0

**Comment by Nonary** [comment]
No response from user
