### ISSUE TITLE
"Switch to the Dummy Monitor Setup (While Streaming)" step is unclear/not working

### ISSUE THREAD

**Issue by doesboknow** [Nonary/MonitorSwapAutomation#59]
Refers to the following:

6. **Switch to the Dummy Monitor Setup (While Streaming):**  
   - With the stream running and using your other device to view your computer:  
     1. On your Windows PC, go to **Settings > System > Display**.  
     2. Change the setting to show only on the dummy display. (This might make your physical monitor go dark, but you’ll still see your PC screen on your remote device.)  
   
   Now your PC is using the dummy monitor as the “main display.”

A dummy display doesn't seem to get created (which I'm guessing would be "Display 3" in my case, since I have 2 monitors). Is it supposed to be created? Or am I intended to simply physically turn my monitor off during this step?

Attached is a log of me trying to set this up for the first time:

[log_1733874392.txt](https://github.com/user-attachments/files/18089822/log_1733874392.txt)

**Comment by Nonary** [comment]
You need to install a dummy plug or virtual display if you intend on using this script, yes?

**Comment by Nonary** [comment]
If you're confused which monitor number click on identify, it will show the numbers on the monitors themselves.

So if you see 2 and 3 for example, then you know the correct one for the dummy plug is 1 in that case.

So you tell windows to "show only on 1" and then follow the next steps 

This was my main concern prior to swapping it to the new backend since this part seems confusing to those who aren't familiar with computers, but unfortunately out of options thanks to 24H2

**Comment by doesboknow** [comment]
> You need to install a dummy plug or virtual display if you intend on using this script, yes?

I knew [Virtual-Display-Driver](https://github.com/itsmikethetech/Virtual-Display-Driver) and dummy plugs existed, but neither of those was stated in the requirements. So I assumed v2.0 of the application had the ability to create a dummy monitor.

Luckily I don't need that functionality anyway. I'm primarily using this application to only enable one monitor, since Moonlight sometimes picks the wrong monitor, but I also like having easy access to my monitor to see if a game's stuttering is my host or my client.

**Comment by Nonary** [comment]
This script is intended to be used with a dummy plug. Doesn't mean you can't use it for any other reason. Regardless since this is not an issue I'm closing out this one.
