### ISSUE TITLE
Sunshine Broken Connections Locks Displays

### ISSUE THREAD

**Issue by distrohelena** [Nonary/MonitorSwapAutomation#60]
Helloo, sorry for creating an issue for this but I didn't see anything related here, and this happened to me yesterday and was a bit of a pain to fix (had to Moonlight from my MacBook to access the MonitorSwapTool and load the primary.cfg manually).

**OS**: Windows 11 23H2
Terminal is set to Windows Console Host.

**Steps to Reproduce:**
Not exactly sure how to reproduce, but the main issue is _IF_ you reconnect to Moonlight, and this connection crashes halfway through RDP handshake, Sunshine never finishes the connection.
If that happens, nothing I can do allows me to "Stop" my Desktop stream, because of an error saying "All sessions must be disconnected before quitting". Nothing I do allows me to Quit, so the script never executes, and my desktop monitor never reverts.
This might be an issue on Sunshine's side, I'll try posting there too.

Thank you for the app! Besides this small issue this has been a lifesaver, as my monitor does not allow 90Hz whatsoever (240Hz with DSC), and the only way to get correct V-Sync/Frame Pacing is through Idd driver + this app.

**Comment by Nonary** [comment]
Try the latest release to see if it works any better 

https://github.com/Nonary/MonitorSwapAutomation/releases/latest

**Comment by Nonary** [comment]
No response from user
