### ISSUE TITLE
Not reverting to Primary.xml

### ISSUE THREAD

**Issue by jabosammy** [Nonary/MonitorSwapAutomation#61]
Hey there,

I'm running Win11 24H2 and your updated script works most of the times (connecting a dummy display and switching my monitors off) when starting a stream.

Unfortunately, I didn't manage to set it up in several tries with several different Primary.xml configs to revert back to my primary configuration. Whenever I end a stream, my monitors stay dark. 

Running `.\MonitorSwitcher.exe -load:.\Primary.xml` works like a charm. It just isn't triggered at the end of a stream apparently.

Btw: where does monitorswitcher.exe come from? I'd like to learn more about this tool.

Thanks a lot for you effort and development!

Sammy

**Comment by Nonary** [comment]
Can you enable debug mode (in settings) and upload the logs folder here after replicating the problem again?

**Comment by jabosammy** [comment]
Turns out that Ctrl+Alt+Shit+Q only quits the Application and doesn't stop it. 

After actually stopping the application, the Script successfully reactivates the Primary setting. Sorry for not realizing that earlier.

Can you still let me know where the monitorswitcher.exe comes from?

**Comment by Nonary** [comment]
It's from source forge, another open source project 

https://sourceforge.net/projects/monitorswitcher/
