### ISSUE TITLE
No option for "show only on {NUMBER}"

### ISSUE THREAD

**Issue by stalonage** [Nonary/MonitorSwapAutomation#63]
Issue is as above. I do not have this option at all, apologies if this is incorrect. 
<img width="578" alt="Screenshot 2024-12-14 020731" src="https://github.com/user-attachments/assets/f36f3a9c-d875-4187-9eb8-954d28395fad" />

**Comment by Nonary** [comment]
According to chatGPT you have to click on 'Disconnect this display' until only two monitors are active, then the option to 'Show only on {NUMBER}' should be visible.

**Comment by wearysky** [comment]
And on top of disconnecting so that you only have two monitors active, at least for me the option only showed up when I was duplicating desktop on 1 and 2. When I had it set to extend, the option wasn't there.

**Comment by Phanledangdoan** [comment]
The option was not there for me either

**Comment by Nonary** [comment]
Updated readme.md on how to make the dummy plug the primary display when using multiple monitors.
