### ISSUE TITLE
Primary monitor doesn't restore after shutdown

### ISSUE THREAD

**Issue by fmichenaud** [Nonary/MonitorSwapAutomation#64]
Hi !

When I use Moonlight and shut down my computer directly via the remote device, upon restarting my PC, the virtual monitor remains active as the primary display. Would it be possible to automatically run the Undo script during the shutdown process?

Additionally, with my Primary configuration, I need to keep my display settings on "Extend these displays." If I select "Show only on 1," after exiting Moonlight, my primary monitor remains off.

Thank you in advance!

I've attached my Primary, Dummy and latest log file.
[log_1734792156.txt](https://github.com/user-attachments/files/18218701/log_1734792156.txt)

Primary config:

`<?xml version="1.0" encoding="utf-8"?><displaySettings><pathInfoArray><DisplayConfigPathInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><sourceInfo><adapterId><LowPart>131805</LowPart><HighPart>0</HighPart></adapterId><id>0</id><modeInfoIdx>1</modeInfoIdx><statusFlags>InUse</statusFlags></sourceInfo><targetInfo><adapterId><LowPart>131805</LowPart><HighPart>0</HighPart></adapterId><id>256</id><modeInfoIdx>0</modeInfoIdx><outputTechnology>Hdmi</outputTechnology><rotation>Identity</rotation><scaling>Identity</scaling><refreshRate><numerator>60</numerator><denominator>1</denominator></refreshRate><scanLineOrdering>Progressive</scanLineOrdering><targetAvailable>true</targetAvailable><statusFlags>InUse</statusFlags></targetInfo><flags>1</flags></DisplayConfigPathInfo><DisplayConfigPathInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><sourceInfo><adapterId><LowPart>59974</LowPart><HighPart>0</HighPart></adapterId><id>0</id><modeInfoIdx>3</modeInfoIdx><statusFlags>InUse</statusFlags></sourceInfo><targetInfo><adapterId><LowPart>59974</LowPart><HighPart>0</HighPart></adapterId><id>4352</id><modeInfoIdx>2</modeInfoIdx><outputTechnology>Hdmi</outputTechnology><rotation>Identity</rotation><scaling>Identity</scaling><refreshRate><numerator>240</numerator><denominator>1</denominator></refreshRate><scanLineOrdering>Progressive</scanLineOrdering><targetAvailable>true</targetAvailable><statusFlags>InUse</statusFlags></targetInfo><flags>1</flags></DisplayConfigPathInfo></pathInfoArray><modeInfoArray><modeInfo><id>256</id><LUID xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><LowPart>131805</LowPart><HighPart>0</HighPart></LUID><DisplayConfigModeInfoType>Target</DisplayConfigModeInfoType><DisplayConfigTargetMode xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><targetVideoSignalInfo><pixelRate>124416000</pixelRate><hSyncFreq><numerator>64800</numerator><denominator>1</denominator></hSyncFreq><vSyncFreq><numerator>60</numerator><denominator>1</denominator></vSyncFreq><activeSize><cx>1920</cx><cy>1080</cy></activeSize><totalSize><cx>1920</cx><cy>1080</cy></totalSize><videoStandard>USB</videoStandard><ScanLineOrdering>Progressive</ScanLineOrdering></targetVideoSignalInfo></DisplayConfigTargetMode></modeInfo><modeInfo><id>0</id><LUID xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><LowPart>131805</LowPart><HighPart>0</HighPart></LUID><DisplayConfigModeInfoType>Source</DisplayConfigModeInfoType><DisplayConfigSourceMode xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><width>1920</width><height>1080</height><pixelFormat>Pixelformat32Bpp</pixelFormat><position><x>1620</x><y>-1080</y></position></DisplayConfigSourceMode></modeInfo><modeInfo><id>4352</id><LUID xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><LowPart>59974</LowPart><HighPart>0</HighPart></LUID><DisplayConfigModeInfoType>Target</DisplayConfigModeInfoType><DisplayConfigTargetMode xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><targetVideoSignalInfo><pixelRate>2204160000</pixelRate><hSyncFreq><numerator>2204160000</numerator><denominator>5600</denominator></hSyncFreq><vSyncFreq><numerator>240</numerator><denominator>1</denominator></vSyncFreq><activeSize><cx>5120</cx><cy>1440</cy></activeSize><totalSize><cx>5600</cx><cy>1640</cy></totalSize><videoStandard>Other</videoStandard><ScanLineOrdering>Progressive</ScanLineOrdering></targetVideoSignalInfo></DisplayConfigTargetMode></modeInfo><modeInfo><id>0</id><LUID xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><LowPart>59974</LowPart><HighPart>0</HighPart></LUID><DisplayConfigModeInfoType>Source</DisplayConfigModeInfoType><DisplayConfigSourceMode xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><width>5120</width><height>1440</height><pixelFormat>Pixelformat32Bpp</pixelFormat><position><x>0</x><y>0</y></position></DisplayConfigSourceMode></modeInfo></modeInfoArray><additionalInfo><MonitorAdditionalInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><manufactureId>37942</manufactureId><productCodeId>4919</productCodeId><valid>true</valid><monitorDevicePath>XAAAAFwAAAA/AAAAXAAAAEQAAABJAAAAUwAAAFAAAABMAAAAQQAAAFkAAAAjAAAATQAAAFQAAABUAAAAMQAAADMAAAAzAAAANwAAACMAAAAxAAAAJgAAADEAAABhAAAAYQAAAGYAAABiAAAAMwAAAGQAAAA1AAAAJgAAADQAAAAmAAAAVQAAAEkAAABEAAAAMgAAADUAAAA2AAAAIwAAAHsAAABlAAAANgAAAGYAAAAwAAAANwAAAGIAAAA1AAAAZgAAAC0AAABlAAAAZQAAADkAAAA3AAAALQAAADQAAABhAAAAOQAAADAAAAAtAAAAYgAAADAAAAA3AAAANgAAAC0AAAAzAAAAMwAAAGYAAAA1AAAANwAAAGIAAABmAAAANAAAAGUAAABhAAAAYQAAADcAAAB9AAAA</monitorDevicePath><monitorFriendlyDevice>VgAAAEQAAABEAAAAIAAAAGIAAAB5AAAAIAAAAE0AAABUAAAAVAAAAA==</monitorFriendlyDevice></MonitorAdditionalInfo><MonitorAdditionalInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><manufactureId>0</manufactureId><productCodeId>0</productCodeId><valid>false</valid><monitorDevicePath /><monitorFriendlyDevice /></MonitorAdditionalInfo><MonitorAdditionalInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><manufactureId>11596</manufactureId><productCodeId>29851</productCodeId><valid>true</valid><monitorDevicePath>XAAAAFwAAAA/AAAAXAAAAEQAAABJAAAAUwAAAFAAAABMAAAAQQAAAFkAAAAjAAAAUwAAAEEAAABNAAAANwAAADQAAAA5AAAAQgAAACMAAAA1AAAAJgAAADEAAABiAAAAZAAAAGMAAAAyAAAAZgAAAGUAAABkAAAAJgAAADIAAAAmAAAAVQAAAEkAAABEAAAANAAAADMAAAA1AAAAMgAAACMAAAB7AAAAZQAAADYAAABmAAAAMAAAADcAAABiAAAANQAAAGYAAAAtAAAAZQAAAGUAAAA5AAAANwAAAC0AAAA0AAAAYQAAADkAAAAwAAAALQAAAGIAAAAwAAAANwAAADYAAAAtAAAAMwAAADMAAABmAAAANQAAADcAAABiAAAAZgAAADQAAABlAAAAYQAAAGEAAAA3AAAAfQAAAA==</monitorDevicePath><monitorFriendlyDevice>TwAAAGQAAAB5AAAAcwAAAHMAAABlAAAAeQAAACAAAABHAAAAOQAAADMAAABTAAAAQwAAAA==</monitorFriendlyDevice></MonitorAdditionalInfo><MonitorAdditionalInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><manufactureId>0</manufactureId><productCodeId>0</productCodeId><valid>false</valid><monitorDevicePath /><monitorFriendlyDevice /></MonitorAdditionalInfo></additionalInfo></displaySettings>`

Dummy config:
`<?xml version="1.0" encoding="utf-8"?><displaySettings><pathInfoArray><DisplayConfigPathInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><sourceInfo><adapterId><LowPart>131805</LowPart><HighPart>0</HighPart></adapterId><id>0</id><modeInfoIdx>1</modeInfoIdx><statusFlags>InUse</statusFlags></sourceInfo><targetInfo><adapterId><LowPart>131805</LowPart><HighPart>0</HighPart></adapterId><id>256</id><modeInfoIdx>0</modeInfoIdx><outputTechnology>Hdmi</outputTechnology><rotation>Identity</rotation><scaling>Identity</scaling><refreshRate><numerator>60</numerator><denominator>1</denominator></refreshRate><scanLineOrdering>Progressive</scanLineOrdering><targetAvailable>true</targetAvailable><statusFlags>InUse</statusFlags></targetInfo><flags>1</flags></DisplayConfigPathInfo></pathInfoArray><modeInfoArray><modeInfo><id>256</id><LUID xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><LowPart>131805</LowPart><HighPart>0</HighPart></LUID><DisplayConfigModeInfoType>Target</DisplayConfigModeInfoType><DisplayConfigTargetMode xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><targetVideoSignalInfo><pixelRate>442368000</pixelRate><hSyncFreq><numerator>86400</numerator><denominator>1</denominator></hSyncFreq><vSyncFreq><numerator>60</numerator><denominator>1</denominator></vSyncFreq><activeSize><cx>5120</cx><cy>1440</cy></activeSize><totalSize><cx>5120</cx><cy>1440</cy></totalSize><videoStandard>USB</videoStandard><ScanLineOrdering>Progressive</ScanLineOrdering></targetVideoSignalInfo></DisplayConfigTargetMode></modeInfo><modeInfo><id>0</id><LUID xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><LowPart>131805</LowPart><HighPart>0</HighPart></LUID><DisplayConfigModeInfoType>Source</DisplayConfigModeInfoType><DisplayConfigSourceMode xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><width>5120</width><height>1440</height><pixelFormat>Pixelformat32Bpp</pixelFormat><position><x>0</x><y>0</y></position></DisplayConfigSourceMode></modeInfo></modeInfoArray><additionalInfo><MonitorAdditionalInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><manufactureId>37942</manufactureId><productCodeId>4919</productCodeId><valid>true</valid><monitorDevicePath>XAAAAFwAAAA/AAAAXAAAAEQAAABJAAAAUwAAAFAAAABMAAAAQQAAAFkAAAAjAAAATQAAAFQAAABUAAAAMQAAADMAAAAzAAAANwAAACMAAAAxAAAAJgAAADEAAABhAAAAYQAAAGYAAABiAAAAMwAAAGQAAAA1AAAAJgAAADQAAAAmAAAAVQAAAEkAAABEAAAAMgAAADUAAAA2AAAAIwAAAHsAAABlAAAANgAAAGYAAAAwAAAANwAAAGIAAAA1AAAAZgAAAC0AAABlAAAAZQAAADkAAAA3AAAALQAAADQAAABhAAAAOQAAADAAAAAtAAAAYgAAADAAAAA3AAAANgAAAC0AAAAzAAAAMwAAAGYAAAA1AAAANwAAAGIAAABmAAAANAAAAGUAAABhAAAAYQAAADcAAAB9AAAA</monitorDevicePath><monitorFriendlyDevice>VgAAAEQAAABEAAAAIAAAAGIAAAB5AAAAIAAAAE0AAABUAAAAVAAAAA==</monitorFriendlyDevice></MonitorAdditionalInfo><MonitorAdditionalInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><manufactureId>0</manufactureId><productCodeId>0</productCodeId><valid>false</valid><monitorDevicePath /><monitorFriendlyDevice /></MonitorAdditionalInfo></additionalInfo></displaySettings>`

**Comment by Nonary** [comment]
The script only works if you remain logged into the computer. It cannot work from shutdowns because it requires the account to be signed into the computer before applying the restore.
