### ISSUE TITLE
Installer.ps1 does not create proper configuration

### ISSUE THREAD

**Issue by jffz** [Nonary/MonitorSwapAutomation#7]
Was wondering why the install script was not doing its job as I had no changes in my `sunshine.conf` so I played a bit with it.

Looks like the `Set-GlobalPrepCommand` function does not properly generate the json dict in charge of the desired configuration.

I don't have a PR to propose under hand as I end up doing dirty things. Is anyone land here, here is a sample of what the `sunshine.conf` should contain. Indeed, you should adapt paths to your install.

```conf
global_prep_cmd = [{"do":"powershell.exe -executionpolicy bypass -file \"C:\\Users\\<USER>\\Documents\\projects\\community\\MonitorSwapAutomation\\MonitorSwapper.ps1\"","elevated":"false","undo":"powershell.exe -executionpolicy bypass -file \"C:\\Users\\<USER>\\Documents\\projects\\community\\MonitorSwapAutomation\\MonitorSwapper-Functions.ps1\" True"}]
```

**Comment by Nonary** [comment]
You likely did not have Sunshine installed at the default location C:\Program Files and that's why the script couldn't change the configuration

**Comment by jffz** [comment]
I do have it at the default location.
Printing the function output using `Write-Host` output an empty json list

**Comment by Nonary** [comment]
> I do have it at the default location. Printing the function output using `Write-Host` output an empty json list.
> 
> In fact the script added the prep_command to my `sunshine.conf` with an empty json list as value.

Are you using another language than English in Windows? Maybe program files is named differently in other languages?

**Comment by jffz** [comment]
I do use french language but `program files` always resole to the same
windows directory no matter the language.

Also if it was a path issue, it wouldn't have added anything to my config.

Not sure what is wrong here but the issue is that the function handling the
CMD line building does not return the desired value.

I'm no PowerShell expert and don't want to put too much time in it so I
just made it works the dumb way.

Le dim. 18 juin 2023, 18:48, Chase Payne ***@***.***> a
écrit :

**Comment by Nonary** [comment]
Could not replicate this issue.
